baseURL = 'https://codeandcreed.com/'
languageCode = 'en-us'
title = 'Code & Creed'
author = 'Jason Snow'
theme = 'code-creed-theme'

[params]
    description = 'A website project dedicated to bridging the digital and tangible worlds through thoughtful content and design.'
    author = 'Jason Snow'
    title = 'Code & Creed'

[menu]
  [[menu.main]]
    name = "Home"
    pre = "Go Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "Read Latest Posts"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[build]
  minify = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  useShortcuts = true
