baseURL = 'https://codeandcreed.com/'
languageCode = 'en-us'
title = 'Code & Creed'
author = 'Jason Snow'
theme = 'code-creed-theme'

[params]
    description = 'A website project dedicated to bridging the digital and tangible worlds through thoughtful content and design.'
    author = 'Jason Snow'
    title = 'Code & Creed'
    images = ["logo.webp","logo.svg"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "About Code & Creed."
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    pre = "Read our theological and philosophical insights."
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    pre = "Discover our endeavors for God's glory."
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 5

[build]
  minify = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  useShortcuts = true
